In [1]:
'''
Write a Pandas program to implement following operation :- 
• to find and drop the missing values from the given dataset
• to remove the duplicates from the given dataset

Name :- Vishakha U. Chudasama
Enrollment No :- 216270307070
'''

import pandas as pd
import matplotlib.pyplot as plt

df= pd.read_csv('/kaggle/input/nifty50-stock-market-data/TATAMOTORS.csv')

drop_dp = df.dropna()
dupli_df = drop_dp.drop_duplicates()
print("\nOriginal Dataset : - \n",df)
print("\nAfter find and drop the missing values from Dataset :- \n",drop_dp)
print("\nAfter Remove the Duplicates from Dataset :- \n",dupli_df)

Original Dataset : -
             Date      Symbol Series  Prev Close   Open    High     Low  \
0     2000-01-03       TELCO     EQ      201.60  207.4  217.25  207.40
1     2000-01-04       TELCO     EQ      216.75  217.0  219.00  206.00
2     2000-01-05       TELCO     EQ      208.20  194.0  217.80  194.00
3     2000-01-06       TELCO     EQ      213.25  215.0  229.90  215.00
4     2000-01-07       TELCO     EQ      222.10  224.0  239.90  223.10
...          ...         ...    ...         ...    ...     ...     ...
5301  2021-04-26  TATAMOTORS     EQ      294.00  297.0  299.00  294.60
5302  2021-04-27  TATAMOTORS     EQ      295.40  295.7  302.50  295.10
5303  2021-04-28  TATAMOTORS     EQ      301.50  303.5  309.50  303.00
5304  2021-04-29  TATAMOTORS     EQ      305.90  308.9  310.00  301.25
5305  2021-04-30  TATAMOTORS     EQ      301.90  298.2  301.30  292.55

        Last   Close    VWAP    Volume      Turnover    Trades  \
0     217.00  216.75  214.28    676126  1.448775e+13       NaN
1     211.90  208.20  209.50    679215  1.422962e+13       NaN
2     213.10  213.25  210.33   1120951  2.357684e+13       NaN
3     222.00  222.10  225.29   1968998  4.435932e+13       NaN
4     239.90  239.90  236.32   2199431  5.197636e+13       NaN
...      ...     ...     ...       ...           ...       ...
5301  295.85  295.40  296.48  30583139  9.067386e+14  173282.0
5302  302.10  301.50  299.05  35040532  1.047879e+15  191627.0
5303  305.15  305.90  307.22  44668126  1.372278e+15  264159.0
5304  302.20  301.90  304.77  36647292  1.116900e+15  186996.0
5305  293.10  293.85  297.01  36121668  1.072849e+15  227806.0

      Deliverable Volume  %Deliverble
0                    NaN          NaN
1                    NaN          NaN
2                    NaN          NaN
3                    NaN          NaN
4                    NaN          NaN
...                  ...          ...
5301           3291167.0       0.1076
5302           5215100.0       0.1488
5303           5116568.0       0.1145
5304           4193346.0       0.1144
5305           7898988.0       0.2187

[5306 rows x 15 columns]

After find and drop the missing values from Dataset :-
             Date      Symbol Series  Prev Close    Open    High      Low  \
2850  2011-06-01  TATAMOTORS     EQ      1095.3  1096.0  1097.0  1075.60
2851  2011-06-02  TATAMOTORS     EQ      1079.9  1070.0  1070.0  1042.20
2852  2011-06-03  TATAMOTORS     EQ      1048.2  1048.0  1058.0  1014.25
2853  2011-06-06  TATAMOTORS     EQ      1023.8  1011.5  1031.8  1010.25
2854  2011-06-07  TATAMOTORS     EQ      1023.7  1017.0  1033.8  1015.65
...          ...         ...    ...         ...     ...     ...      ...
5301  2021-04-26  TATAMOTORS     EQ       294.0   297.0   299.0   294.60
5302  2021-04-27  TATAMOTORS     EQ       295.4   295.7   302.5   295.10
5303  2021-04-28  TATAMOTORS     EQ       301.5   303.5   309.5   303.00
5304  2021-04-29  TATAMOTORS     EQ       305.9   308.9   310.0   301.25
5305  2021-04-30  TATAMOTORS     EQ       301.9   298.2   301.3   292.55

         Last    Close     VWAP    Volume      Turnover    Trades  \
2850  1077.25  1079.90  1083.36   2412309  2.613407e+14   76698.0
2851  1046.15  1048.20  1050.62   2604237  2.736056e+14   74650.0
2852  1024.60  1023.80  1031.52   3600090  3.713581e+14   94611.0
2853  1022.20  1023.70  1020.38   2076683  2.119014e+14   64914.0
2854  1028.00  1027.20  1027.38   2117760  2.175745e+14   56772.0
...       ...      ...      ...       ...           ...       ...
5301   295.85   295.40   296.48  30583139  9.067386e+14  173282.0
5302   302.10   301.50   299.05  35040532  1.047879e+15  191627.0
5303   305.15   305.90   307.22  44668126  1.372278e+15  264159.0
5304   302.20   301.90   304.77  36647292  1.116900e+15  186996.0
5305   293.10   293.85   297.01  36121668  1.072849e+15  227806.0

      Deliverable Volume  %Deliverble
2850           1152083.0       0.4776
2851           1149341.0       0.4413
2852           1472425.0       0.4090
2853            451682.0       0.2175
2854            805423.0       0.3803
...                  ...          ...
5301           3291167.0       0.1076
5302           5215100.0       0.1488
5303           5116568.0       0.1145
5304           4193346.0       0.1144
5305           7898988.0       0.2187

[2456 rows x 15 columns]

After Remove the Duplicates from Dataset :-
             Date      Symbol Series  Prev Close    Open    High      Low  \
2850  2011-06-01  TATAMOTORS     EQ      1095.3  1096.0  1097.0  1075.60
2851  2011-06-02  TATAMOTORS     EQ      1079.9  1070.0  1070.0  1042.20
2852  2011-06-03  TATAMOTORS     EQ      1048.2  1048.0  1058.0  1014.25
2853  2011-06-06  TATAMOTORS     EQ      1023.8  1011.5  1031.8  1010.25
2854  2011-06-07  TATAMOTORS     EQ      1023.7  1017.0  1033.8  1015.65
...          ...         ...    ...         ...     ...     ...      ...
5301  2021-04-26  TATAMOTORS     EQ       294.0   297.0   299.0   294.60
5302  2021-04-27  TATAMOTORS     EQ       295.4   295.7   302.5   295.10
5303  2021-04-28  TATAMOTORS     EQ       301.5   303.5   309.5   303.00
5304  2021-04-29  TATAMOTORS     EQ       305.9   308.9   310.0   301.25
5305  2021-04-30  TATAMOTORS     EQ       301.9   298.2   301.3   292.55

         Last    Close     VWAP    Volume      Turnover    Trades  \
2850  1077.25  1079.90  1083.36   2412309  2.613407e+14   76698.0
2851  1046.15  1048.20  1050.62   2604237  2.736056e+14   74650.0
2852  1024.60  1023.80  1031.52   3600090  3.713581e+14   94611.0
2853  1022.20  1023.70  1020.38   2076683  2.119014e+14   64914.0
2854  1028.00  1027.20  1027.38   2117760  2.175745e+14   56772.0
...       ...      ...      ...       ...           ...       ...
5301   295.85   295.40   296.48  30583139  9.067386e+14  173282.0
5302   302.10   301.50   299.05  35040532  1.047879e+15  191627.0
5303   305.15   305.90   307.22  44668126  1.372278e+15  264159.0
5304   302.20   301.90   304.77  36647292  1.116900e+15  186996.0
5305   293.10   293.85   297.01  36121668  1.072849e+15  227806.0

      Deliverable Volume  %Deliverble
2850           1152083.0       0.4776
2851           1149341.0       0.4413
2852           1472425.0       0.4090
2853            451682.0       0.2175
2854            805423.0       0.3803
...                  ...          ...
5301           3291167.0       0.1076
5302           5215100.0       0.1488
5303           5116568.0       0.1145
5304           4193346.0       0.1144
5305           7898988.0       0.2187

[2456 rows x 15 columns]