In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
'''
• to convert a NumPy array to a Pandas series
Name :- Vishakha U. Chudasama
Enrollment No :- 216270307070
'''

a = [23, 56, 90, 12, 90, 11]
arr = np.array(a)

panda_arr = pd.Series(arr)
print("\nAfter Numpy Array is = \n",arr)

print("\nBefore Pandas Series is = \n", panda_arr)

In [ ]:
'''
• to convert the first column of a DataFrame as a Series.
Name :- Vishakha U. Chudasama
Enrollment No :- 216270307070
'''

# Create a DataFrame
data = {'numbers': ['1st', '2nd', '3rd', '4th'],
        'colors': ['Mango', 'Guavava', 'Apple', 'Strawberry']}
df = pd.DataFrame(data)

first_column_series = df.iloc[:, 0]

# Print the original DataFrame
print("Original DataFrame : \n", df)

# Print the extracted Series
print("\nFirst Column as a Series : \n", first_column_series)

In [ ]:
'''
• to create the mean and standard deviation of the data of a given Series 
Name :- Vishakha U. Chudasama
Enrollment No :- 216270307070
'''

series = pd.Series([67, 23, 67, 98, 45])

# Calculate the mean and standard deviation
mean_value = series.mean()
std_deviation = series.std()

print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)

In [ ]:
'''
• to sort a given Series.
Name :- Vishakha U. Chudasama
Enrollment No :- 216270307070
'''

series = pd.Series([45, 87, 99, 12, 35, 73, 25])

sorted_series = series.sort_values()

print("Sorted Series : \n", sorted_series)
print(sorted_series)